title: Ning Zhu's Homepage
page-top-title: Ning Zhu
top-section-bg-text: Be what you wanna be
home-subtitle: Ning Zhu &ensp;|&ensp; 朱凝
copyright-text: '&copy; Ning Zhu 2023-2025. All Rights Reserved.'
